 package parser;

// Default libraries
import stackable.*;
import robot.*;
import java.util.Vector;

/**
 * Parser for program test/answer.java.
 * This file is automatically 
 * generated by parser.pl
 * @author parser.pl
 */
public class Parser
{
    /** 
     * Method for uploading the program.
     */
    public Vector<Command> upload()
    {
        Vector<Command> PROG = new Vector<Command>();

        Num n10 = new Num(10);
        Num n13 = new Num(13);
        PROG.add(new Command("PUSH", n13 , null));
        PROG.add(new Command("PUSH", n10 , null));
        PROG.add(new Command("MOD",  null, null));
        PROG.add(new Command("DUP",  null, null));
        PROG.add(new Command("PUSH", n13 , null));
        PROG.add(new Command("MUL",  null, null));
        PROG.add(new Command("ADD",  null, null));
        PROG.add(new Command("DUP",  null, null));
        PROG.add(new Command("PRN",  null, null));
        PROG.add(new Command("PUSH", n10 , null));
        PROG.add(new Command("DIV",  null, null));
        PROG.add(new Command("PRN",  null, null));
        PROG.add(new Command("END",  null, null));
        PROG.add(null);

        return PROG;
    }
}

